# Generated by Django 2.1 on 2018-08-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_PU',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_Q',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_sell',
            field=models.IntegerField(null=True),
        ),
    ]
