# Generated by Django 2.1 on 2018-08-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0002_auto_20180811_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hist_date', models.DateField()),
                ('hist_nbr_sell', models.IntegerField()),
                ('hist_money', models.IntegerField()),
                ('hist_prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendeur.Product')),
            ],
        ),
    ]
