# Generated by Django 2.1 on 2018-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0003_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vend_name', models.TextField()),
                ('vend_code_venduer', models.TextField()),
                ('vend_sells', models.IntegerField()),
                ('vend_abs', models.IntegerField()),
                ('vend_money', models.IntegerField()),
            ],
        ),
    ]
