# Generated by Django 2.1 on 2018-08-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0004_vendeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='vend_abs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='vend_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='vend_sells',
            field=models.IntegerField(default=0),
        ),
    ]
