# Generated by Django 2.1 on 2018-08-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0005_auto_20180829_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendeur',
            old_name='vend_code_venduer',
            new_name='vend_code',
        ),
    ]
