# Generated by Django 2.1 on 2018-09-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0007_history_hist_prix_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='hist_money',
            field=models.BigIntegerField(),
        ),
    ]
