# Generated by Django 2.1 on 2018-09-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0008_auto_20180904_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
