# Generated by Django 2.1 on 2018-09-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0009_auto_20180907_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_id',
        ),
    ]
