# Generated by Django 2.1 on 2018-09-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0010_remove_product_prod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='hist_etat',
            field=models.TextField(default='payé'),
        ),
    ]
