# Generated by Django 2.1 on 2018-09-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0011_history_hist_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='hist_etat',
            field=models.IntegerField(default=0),
        ),
    ]
