# Generated by Django 2.1 on 2018-09-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0012_auto_20180908_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='vend_user_name',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
