# Generated by Django 2.1 on 2018-09-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0013_vendeur_vend_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='vend_coockie_hash',
            field=models.BigIntegerField(default=0),
        ),
    ]
