# Generated by Django 2.1 on 2018-09-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0014_vendeur_vend_coockie_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='vend_coockie_hash',
            field=models.TextField(default=''),
        ),
    ]
