# Generated by Django 2.1 on 2018-09-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0016_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_bis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_coockie_hash', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendeur.vendeur')),
            ],
        ),
    ]
