# Generated by Django 2.1 on 2018-09-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0017_user_bis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendeur',
            name='vend_coockie_hash',
        ),
    ]
